apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scale-pods
spec:
  schedule: "0 23 * * *" # Schedule the job to run every day at 23:00
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: your-image-pull-secret
          containers:
            - name: scaler
              image: YOUR_IMAGE_NAME
              command: ["/bin/bash", "-c"]
              args: ["kubectl scale deployment your-deployment-name --replicas=10"]
          restartPolicy: OnFailure